import type { MenuPoolEntry } from "@/types/menu-decider";

export const MENU_POOL: readonly MenuPoolEntry[] = [
  { name: "칼국수", category: "한식·면", tags: ["따끈한", "비오는날", "점심"] },
  { name: "들깨칼국수", category: "한식·면", tags: ["따끈한", "고소한", "든든한"] },
  { name: "잔치국수", category: "한식·면", tags: ["가벼운", "따끈한", "점심"] },
  { name: "비빔국수", category: "한식·면", tags: ["매콤한", "시원한", "여름"] },
  { name: "막국수", category: "한식·면", tags: ["시원한", "여름", "매콤한"] },
  { name: "메밀국수", category: "한식·면", tags: ["시원한", "여름", "가벼운"] },
  { name: "만두국", category: "한식·면", tags: ["따끈한", "든든한", "겨울"] },
  { name: "수제비", category: "한식·면", tags: ["따끈한", "비오는날"] },
  { name: "쌀국수", category: "아시안", tags: ["따끈한", "가벼운", "해장"] },
  { name: "라면", category: "한식·면", tags: ["매콤한", "야식", "혼밥"] },
  { name: "비빔라면", category: "한식·면", tags: ["매콤한", "혼밥"] },

  { name: "김치찌개", category: "한식·찌개", tags: ["따끈한", "매콤한", "든든한"] },
  { name: "된장찌개", category: "한식·찌개", tags: ["따끈한", "든든한", "정겨운"] },
  { name: "부대찌개", category: "한식·찌개", tags: ["든든한", "매콤한", "여럿이"] },
  { name: "순두부찌개", category: "한식·찌개", tags: ["따끈한", "부드러운", "매콤한"] },
  { name: "청국장", category: "한식·찌개", tags: ["구수한", "따끈한", "건강한"] },
  { name: "비지찌개", category: "한식·찌개", tags: ["따끈한", "구수한", "든든한"] },
  { name: "갈비탕", category: "한식·국밥", tags: ["따끈한", "든든한", "보양"] },
  { name: "설렁탕", category: "한식·국밥", tags: ["따끈한", "담백한", "해장"] },
  { name: "곰탕", category: "한식·국밥", tags: ["따끈한", "담백한", "보양"] },
  { name: "삼계탕", category: "한식·국밥", tags: ["보양", "여름", "든든한"] },
  { name: "감자탕", category: "한식·국밥", tags: ["매콤한", "든든한", "여럿이"] },
  { name: "추어탕", category: "한식·국밥", tags: ["보양", "구수한"] },
  { name: "육개장", category: "한식·국밥", tags: ["매콤한", "따끈한", "해장"] },

  { name: "순대국밥", category: "한식·국밥", tags: ["따끈한", "해장", "든든한"] },
  { name: "돼지국밥", category: "한식·국밥", tags: ["따끈한", "해장", "든든한"] },
  { name: "콩나물국밥", category: "한식·국밥", tags: ["가벼운", "해장", "따끈한"] },
  { name: "해장국", category: "한식·국밥", tags: ["해장", "따끈한"] },
  { name: "황태해장국", category: "한식·국밥", tags: ["해장", "담백한", "따끈한"] },
  { name: "선지해장국", category: "한식·국밥", tags: ["해장", "든든한"] },

  { name: "삼겹살", category: "한식·구이", tags: ["여럿이", "저녁", "든든한"] },
  { name: "목살구이", category: "한식·구이", tags: ["여럿이", "저녁"] },
  { name: "양념갈비", category: "한식·구이", tags: ["여럿이", "달짝지근한"] },
  { name: "닭갈비", category: "한식·구이", tags: ["매콤한", "여럿이"] },
  { name: "곱창구이", category: "한식·구이", tags: ["야식", "여럿이", "든든한"] },
  { name: "막창", category: "한식·구이", tags: ["야식", "여럿이"] },
  { name: "불고기", category: "한식·구이", tags: ["달짝지근한", "여럿이", "든든한"] },

  { name: "비빔밥", category: "한식·밥", tags: ["가벼운", "혼밥", "점심"] },
  { name: "돌솥비빔밥", category: "한식·밥", tags: ["따끈한", "든든한", "혼밥"] },
  { name: "산채비빔밥", category: "한식·밥", tags: ["가벼운", "건강한"] },
  { name: "보리밥", category: "한식·밥", tags: ["담백한", "건강한"] },
  { name: "콩나물밥", category: "한식·밥", tags: ["담백한", "혼밥"] },
  { name: "백반", category: "한식·밥", tags: ["담백한", "든든한", "혼밥"] },
  { name: "쌈밥", category: "한식·밥", tags: ["건강한", "여럿이"] },
  { name: "오므라이스", category: "양식·밥", tags: ["부드러운", "혼밥", "점심"] },
  { name: "카레라이스", category: "양식·밥", tags: ["든든한", "혼밥"] },
  { name: "볶음밥", category: "중식·밥", tags: ["든든한", "혼밥", "점심"] },
  { name: "김치볶음밥", category: "한식·밥", tags: ["매콤한", "혼밥"] },

  { name: "갈비찜", category: "한식·찜", tags: ["여럿이", "든든한", "달짝지근한"] },
  { name: "찜닭", category: "한식·찜", tags: ["여럿이", "매콤한"] },
  { name: "아구찜", category: "한식·찜", tags: ["매콤한", "여럿이"] },
  { name: "해물찜", category: "한식·찜", tags: ["매콤한", "여럿이"] },
  { name: "보쌈", category: "한식·찜", tags: ["여럿이", "야식"] },
  { name: "족발", category: "한식·찜", tags: ["야식", "여럿이"] },

  { name: "회", category: "한식·해산물", tags: ["담백한", "여럿이"] },
  { name: "회덮밥", category: "한식·해산물", tags: ["가벼운", "혼밥", "점심"] },
  { name: "초밥", category: "일식", tags: ["가벼운", "혼밥"] },
  { name: "매운탕", category: "한식·해산물", tags: ["매콤한", "여럿이", "따끈한"] },
  { name: "대구탕", category: "한식·해산물", tags: ["담백한", "해장", "따끈한"] },
  { name: "알탕", category: "한식·해산물", tags: ["매콤한", "해장"] },
  { name: "굴국밥", category: "한식·국밥", tags: ["따끈한", "겨울", "해장"] },
  { name: "굴짬뽕", category: "중식", tags: ["따끈한", "겨울", "매콤한"] },

  { name: "떡볶이", category: "분식", tags: ["매콤한", "혼밥", "간식"] },
  { name: "로제떡볶이", category: "분식", tags: ["매콤한", "달콤한"] },
  { name: "김밥", category: "분식", tags: ["가벼운", "혼밥", "점심"] },
  { name: "충무김밥", category: "분식", tags: ["가벼운", "혼밥"] },
  { name: "라볶이", category: "분식", tags: ["매콤한", "혼밥", "간식"] },
  { name: "순대", category: "분식", tags: ["혼밥", "간식"] },
  { name: "튀김", category: "분식", tags: ["간식", "혼밥"] },
  { name: "어묵", category: "분식", tags: ["따끈한", "간식", "겨울"] },
  { name: "토스트", category: "분식", tags: ["가벼운", "아침"] },
  { name: "샌드위치", category: "양식", tags: ["가벼운", "아침", "혼밥"] },

  { name: "짜장면", category: "중식", tags: ["혼밥", "점심", "달짝지근한"] },
  { name: "간짜장", category: "중식", tags: ["혼밥", "달짝지근한"] },
  { name: "짬뽕", category: "중식", tags: ["매콤한", "따끈한", "해장"] },
  { name: "볶음짬뽕", category: "중식", tags: ["매콤한"] },
  { name: "탕수육", category: "중식", tags: ["여럿이", "달짝지근한"] },
  { name: "마파두부", category: "중식", tags: ["매콤한", "부드러운"] },
  { name: "깐풍기", category: "중식", tags: ["매콤한", "여럿이"] },
  { name: "양장피", category: "중식", tags: ["가벼운", "여럿이"] },
  { name: "마라탕", category: "중식", tags: ["매콤한", "따끈한", "혼밥"] },
  { name: "마라샹궈", category: "중식", tags: ["매콤한", "여럿이"] },
  { name: "딤섬", category: "중식", tags: ["여럿이", "가벼운"] },

  { name: "우동", category: "일식", tags: ["따끈한", "가벼운", "비오는날"] },
  { name: "라멘", category: "일식", tags: ["따끈한", "든든한", "야식"] },
  { name: "츠케멘", category: "일식", tags: ["여름", "진한"] },
  { name: "돈카츠", category: "일식", tags: ["든든한", "혼밥"] },
  { name: "치킨카츠", category: "일식", tags: ["든든한", "혼밥"] },
  { name: "카츠동", category: "일식", tags: ["든든한", "혼밥"] },
  { name: "텐동", category: "일식", tags: ["든든한", "혼밥"] },
  { name: "규동", category: "일식", tags: ["든든한", "혼밥"] },
  { name: "오야코동", category: "일식", tags: ["든든한", "혼밥"] },
  { name: "사케동", category: "일식", tags: ["가벼운", "담백한"] },
  { name: "오니기리", category: "일식", tags: ["가벼운", "혼밥", "아침"] },

  { name: "파스타", category: "양식", tags: ["혼밥", "점심"] },
  { name: "토마토파스타", category: "양식", tags: ["가벼운", "혼밥"] },
  { name: "크림파스타", category: "양식", tags: ["부드러운", "느끼한"] },
  { name: "알리오올리오", category: "양식", tags: ["가벼운", "혼밥"] },
  { name: "라자냐", category: "양식", tags: ["든든한", "여럿이"] },
  { name: "리조또", category: "양식", tags: ["부드러운", "든든한"] },
  { name: "피자", category: "양식", tags: ["여럿이", "야식"] },
  { name: "햄버거", category: "양식", tags: ["든든한", "혼밥"] },
  { name: "스테이크", category: "양식", tags: ["든든한", "여럿이", "저녁"] },
  { name: "샐러드", category: "양식", tags: ["가벼운", "건강한", "혼밥"] },
  { name: "오믈렛", category: "양식", tags: ["가벼운", "아침"] },
  { name: "에그베네딕트", category: "양식", tags: ["가벼운", "아침"] },
  { name: "팬케이크", category: "디저트", tags: ["달콤한", "아침"] },
  { name: "와플", category: "디저트", tags: ["달콤한", "간식"] },
  { name: "크로플", category: "디저트", tags: ["달콤한", "간식"] },
  { name: "브런치", category: "양식", tags: ["가벼운", "아침"] },
  { name: "그라탕", category: "양식", tags: ["부드러운", "겨울"] },
  { name: "리소토", category: "양식", tags: ["부드러운", "든든한"] },

  { name: "팟타이", category: "아시안", tags: ["혼밥", "달콤한"] },
  { name: "똠얌꿍", category: "아시안", tags: ["매콤한", "여럿이"] },
  { name: "카오팟", category: "아시안", tags: ["혼밥", "점심"] },
  { name: "분짜", category: "아시안", tags: ["가벼운", "여름"] },
  { name: "월남쌈", category: "아시안", tags: ["가벼운", "여럿이"] },
  { name: "나시고렝", category: "아시안", tags: ["매콤한", "혼밥"] },

  { name: "치킨", category: "야식·치킨", tags: ["야식", "여럿이"] },
  { name: "양념치킨", category: "야식·치킨", tags: ["야식", "매콤한"] },
  { name: "후라이드", category: "야식·치킨", tags: ["야식", "여럿이"] },
  { name: "간장치킨", category: "야식·치킨", tags: ["야식", "달짝지근한"] },
  { name: "마라치킨", category: "야식·치킨", tags: ["야식", "매콤한"] },

  { name: "타코", category: "양식", tags: ["가벼운", "여럿이"] },
  { name: "부리또", category: "양식", tags: ["든든한", "혼밥"] },
  { name: "퀘사디아", category: "양식", tags: ["가벼운", "여럿이"] },
  { name: "케밥", category: "양식", tags: ["혼밥", "든든한"] },
  { name: "팔라펠", category: "양식", tags: ["가벼운", "건강한"] },

  { name: "냉면", category: "한식·면", tags: ["시원한", "여름"] },
  { name: "물냉면", category: "한식·면", tags: ["시원한", "여름", "담백한"] },
  { name: "비빔냉면", category: "한식·면", tags: ["매콤한", "여름"] },
  { name: "평양냉면", category: "한식·면", tags: ["담백한", "여름"] },

  { name: "곱창전골", category: "한식·찌개", tags: ["여럿이", "야식", "든든한"] },
  { name: "버섯전골", category: "한식·찌개", tags: ["담백한", "여럿이"] },
  { name: "두부전골", category: "한식·찌개", tags: ["담백한", "가벼운"] },

  { name: "전", category: "한식·전", tags: ["비오는날", "여럿이"] },
  { name: "파전", category: "한식·전", tags: ["비오는날", "여럿이"] },
  { name: "김치전", category: "한식·전", tags: ["비오는날", "여럿이"] },
  { name: "감자전", category: "한식·전", tags: ["비오는날", "여럿이"] },
  { name: "녹두전", category: "한식·전", tags: ["여럿이", "담백한"] },
] as const;

export function isMenuInPool(name: string): boolean {
  return MENU_POOL.some((entry) => entry.name === name);
}

export function findMenuEntry(name: string): MenuPoolEntry | undefined {
  return MENU_POOL.find((entry) => entry.name === name);
}
